### ISSUE TITLE
Basic Course Search, UX improvements + CSV download 

### ISSUE THREAD

**Issue by pconrad** [ucsb-cs156-s21/proj-ucsb-courses-search#1]
* 

- ~~List the full course title instead of the abbreviated name on GOLD~~ (we already display as much title info as we have)
- ~~List sections in chronological order instead of in enroll code order~~   moved to issue #232 
- ~~List times in 12 hour format instead of 24 hour format~~ moved to issue #235 
- ~~Make quarter and course level human-readable~~
- ~~Quarter should not be displayed as “20201”~~
- ~~Level should not be just “U”~~ level is not displayed, maybe we could consider adding that
- ~~Display “N/A” for classes / sections without a TA / instructor~~
- ~~Hide classes that are canceled, closed, or have 0 student capacity~~
- ~~Course number column should come first, not quarter~~
- ~~Allow a course’s sections to be collapsible under the lecture~~ moved to issue #236
- ~~Alternate background colors for courses in course search results~~
- ~~Make the table header sticky (meaning it stays on the screen when you scroll)~~ moved to issue #237
- ~~Give classes that are full, canceled, or have 0 capacity a different color~~
- ~~Consider using a different font / font size for sections versus lectures~~ moved to issue #238

CSV Download:

* As a user, from any courses search, I can press a "download as CSV" button, and get the results of that search in CSV format.

Add Course Button 

The personal schedule team may, temporarily, have a separate version of the course results that has a button on it to add courses to the personal schedule.    This is just a temporary measure to avoid a conflict between the teams.   Once they have completed their initial version, incorporate that button into the permanent version.

**Comment by mara-downing** [comment]
Moved to smaller issues for s21
