### ISSUE TITLE
Start and End Quarter are configurable in the application.properties file

### ISSUE THREAD

**Issue by pconrad** [ucsb-cs156-s21/proj-ucsb-courses-search#18]
# User Story

Basic: As a user, I can enter a quarter, department, and a course level, and see a list of courses.

More specific: As a user I can enter any quarter between a specified start and end quarter that are configured in the application.properties file, not just quarters that are hard coded.

# Acceptance Criteria

- [ ] There is an application specific configuration property for start quarter and end quarter.
- [ ] There are instructions in the README for configuration of this property
- [ ] On the basic course search form, there drop down for quarter allows any value between the start ane end quarters, inclusive.

**Comment by btk5h** [comment]
Superceded by #186
