### ISSUE TITLE
Add M21 to menu on main page

### ISSUE THREAD

**Issue by pconrad** [ucsb-cs156-s21/proj-ucsb-courses-search#223]
# User Story

As a user I can get courses from M21 so that I can see information for Summer 21

# Acceptance Criteria

- [ ] On the main page, the quarter menu, which currently only includes F20, W21, and S21, also includes M21
- [ ] When searching with M21, information for Summer 2021 courses is shown.

# Implementation Todos

Front end:

- [ ] Add option to menu in `BasicCourseSearchForm.js`

**Comment by btk5h** [comment]
Short-term solution, implementing #185 is preferable
