### ISSUE TITLE
Deploy new favicon with storke tower image

### ISSUE THREAD

**Issue by mara-downing** [ucsb-cs156-s21/proj-ucsb-courses-search#251]
# User Story

* As a user
* I can see a favicon relevant to the project
* So that I can easily spot browser tabs for this app

# Discussion

In a browser, there are typically icons on each tab that identify the application.  For example, these:

![image](https://user-images.githubusercontent.com/1119017/108134964-0a81f500-706c-11eb-8475-4e7ea223674d.png)

We want to change ours to be:

![favicon-ucsb-courses-search](https://user-images.githubusercontent.com/72156992/117895685-befa7400-b273-11eb-8a7a-42bd17b89a88.png)

# Acceptance Criteria

- [x] When the application is loaded in a browser, we see the correct favicon for this app

# Implementation todos

- [x] Replace the file `javascript/public/favicon.ico` with a new `favicon.ico` file (png for creating this file is linked above).
- [x] Upload the `.png` file above into the directory `javascript/public`.
- [x] In the file `javascript/public/index.html`, replace the favicon lines to use the new favicon 

# Testing

Because this is in static code rather than Java or JavaScript code, we do not currently have a good way to write automated tests for this.  So this should be tested manually by implementing first on localhost, then by deploying the branch on the team's QA site.

Also, all existing tests should still pass.

**Comment by pconrad** [comment]
Here is the new favicon:

![proj-ucsb-courses-search-new-favicon](https://user-images.githubusercontent.com/1119017/117862495-8e9ce080-b247-11eb-9688-9ab0b78cc93e.png)
