### ISSUE TITLE
Search by course over time

### ISSUE THREAD

**Issue by pconrad** [ucsb-cs156-s21/proj-ucsb-courses-search#3]
In this epic, we add the ability to do some searches related to a specific course over time.

You'll be offered some way to choose a specific course, e.g. CMPSC 130A, either by typing in the course name/number, or by searching in some way and selecting it from a list.

Then you'll be offered the ability to specify a start and end quarter.  

Then you'll be shown information about that course over time.  (Note that this requires doing separate API searches, and combining the results together.)

Information might include:
* A full list of all offerings of the course
* Summary of which professors have taught the course, and in which quarters (e.g. same information, but sorted by professor)
* What % of the time is the course offered in F, W, S and M (summer?) (and in which years was it offered in each of those?  This can help students guess how likely is it to be offered in a particular quarter based on past data.)
* What are the capacities and enrollment numbers over time?   These could be presented in a chart, or a graph.

**Comment by mara-downing** [comment]
Closed, mostly done but moved interesting single course statistics to #240
