### ISSUE TITLE
Hide Add column in courses search results when not logged in

### ISSUE THREAD

**Issue by Mitchell57** [ucsb-cs156-s21/proj-ucsb-courses-search#40]
# User Story

As a user the Add column is hidden in search results when I am not logged in so I am not confused about the empty column.

# Acceptance Criteria

- [x] If not logged in, there is no Add column visible in the returned search results.
- [x] There is still an add button located in the Add column next to each eligible course (either lecture or section) when users are logged in

Front end:

- [x] Check if user is logged in to display Add column in table.

Testing:

- [x] Front end tests pass and there is adequate coverage
- [x] Back end tests pass and there is adequate coverage

Notes :
(from Andrea)

-   Remove Add column in Course Search 
    -   when logged in you get a "role" 
    -   so we can check this to determine if we should change the front end table 
    -   In RoleController.js toward the bottom we can see the role controller 
    -   In BasicCourseTable.js (https://github.com/ucsb-cs156-s21/proj-ucsb-courses-search/blob/main/javascript/src/main/components/BasicCourseSearch/BasicCourseTable.js)
        - remove or hide the column based on the role : (https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/column-props.html)

    - See AppNavabar.js  for similar implementation

    Tip: in github use the search bar to search in the repository for keywords like "add role" to see where else its used
    (or control -shift-F to do the same in local VS code repo)

    - Use this end point to determine if the user has a role or not 
    const hasRole = api/myRole

**Comment by pconrad** [comment]
@mara-downing I think this one is already done?   I think we should probably close it.

**Comment by pconrad** [comment]
Or, per discussion on Slack, maybe repurpose this to an issue that removes the add column from the table when the user is not logged in.
