### ISSUE TITLE
Add extra elements to basic search CSV download

### ISSUE THREAD

**Issue by kunalhandaUCSB** [ucsb-cs156-s21/proj-ucsb-courses-search#78]
# User Story

As a user I can see the instructor, enroll code, unit, enrolled, and max value when I download the CSV in addition to the previous elements.

# Acceptance Criteria

- [ ] The CSV download file has the above elements for a given search

# Implementation Todos

Front end:

- [ ] Extract the necessary information from the JSON and add to CSV output 

Testing:

- [ ] Front end tests pass and there is adequate coverage
-- [ ] Back end tests pass and there is adequate coverage

**Comment by mara-downing** [comment]
CSV download is looking good at the moment
