### ISSUE TITLE
FOR W21 (not for F20): replace hard coded department list with API call

### ISSUE THREAD

**Issue by pconrad** [ucsb-cs156-s21/proj-ucsb-courses-search#82]
In `javascript/src/main/components/Statistics/DepartmentFormSelect.js` there is a hard coded list of departments.  Replace this with a backend service that gets this list of departments from the api:

`https://api.ucsb.edu/students/lookups/v1/departments`

**Comment by btk5h** [comment]
Duplicate of #19
